TebLocalPlannerROS:

 odom_topic: odom
 map_frame: map

 # Trajectory

 teb_autosize: True
 dt_ref: 0.3
 dt_hysteresis: 0.1
 global_plan_overwrite_orientation: True
 max_global_plan_lookahead_dist: 3.0
 feasibility_check_no_poses: 5

 # Robot

 max_vel_x: 0.4
 max_vel_x_backwards: 0.2
 max_vel_theta: 0.3
 acc_lim_x: 0.5
 acc_lim_theta: 0.1
 max_vel_y: 0.4
 max_vel_y_backwards: 0.2
 acc_lim_y: 0.5

 min_turning_radius: 0.0
 footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
   type: "point"


 # GoalTolerance

 xy_goal_tolerance: 0.2
 yaw_goal_tolerance: 0.1
 free_goal_vel: False

 # Obstacles

 min_obstacle_dist: 0.4
 include_costmap_obstacles: True
 costmap_obstacles_behind_robot_dist: 1.0
 obstacle_poses_affected: 30
 costmap_converter_plugin: ""
 costmap_converter_spin_thread: True
 costmap_converter_rate: 6

 # Optimization

 no_inner_iterations: 5
 no_outer_iterations: 4
 optimization_activate: True
 optimization_verbose: False
 penalty_epsilon: 0.05 #0.1
 weight_max_vel_x: 2
 weight_max_vel_y: 2
 weight_max_vel_theta: 1
 weight_acc_lim_x: 1
 weight_acc_lim_y: 1
 weight_acc_lim_theta: 1
 weight_kinematics_nh: 1 # Specifies the weight for satisfying the non-holonomic constraint by the optimizer and is usually set to a high value for non-holonomic robots.
 weight_kinematics_forward_drive: 1
 weight_kinematics_turning_radius: 1
 weight_optimaltime: 1
 weight_obstacle: 50
 weight_dynamic_obstacle: 10 # not in use yet
 alternative_time_cost: False # not in use yet

 # Homotopy Class Planner

 enable_homotopy_class_planning: True
 enable_multithreading: True
 simple_exploration: False
 max_number_classes: 4
 roadmap_graph_no_samples: 15
 roadmap_graph_area_width: 5
 h_signature_prescaler: 0.5
 h_signature_threshold: 0.1
 obstacle_keypoint_offset: 0.1
 obstacle_heading_threshold: 0.45
 visualize_hc_graph: False

# http://wiki.ros.org/base_local_planner#Parameters
TrajectoryPlannerROS:

  # Robot configuration
  acc_lim_x: 10.0
  acc_lim_theta: 10.0
  max_vel_x: 3.0
  min_vel_x: 0.0
  max_vel_theta: 3.0
  min_vel_theta: -0.5
  min_in_place_vel_theta: 1.0
  escape_vel: -0.1
  holonomic_robot: false

  # Goal tolerance
  #yaw_goal_tolerance: 0.1
  #yaw_goal_tolerance: 1.57
  yaw_goal_tolerance: 6.28
  #xy_goal_tolerance: 0.2
  xy_goal_tolerance: 0.4
  latch_xy_goal_tolerance: true

  # Forward simulation
  sim_time: 3.0
  sim_granularity: 0.05
  angular_sim_granularity: 0.025
  vx_samples: 20
  vtheta_samples: 20

  # Trajectory scoring
  meter_scoring: true
  path_distance_bias: 1.0 # was 0.5
  goal_distance_bias: 0.3
  occdist_scale: 0.005
  heading_lookahead: 0.325
  heading_scoring: false
  heading_scoring_timestep: 0.8
  dwa: true
  publish_cost_grid_pc: false
  global_frame_id: odom

  # Oscillation
  oscillation_reset_dist: 0.05

  # Global plan
  prune_plan: true
