# http://wiki.ros.org/costmap_2d#costmap_2d.2BAC8-layered.Parameters
global_costmap:
#was map now odom
  global_frame: map
  robot_base_frame: fake
  transform_tolerance: 0.5
# update from 2.0 to 4.0 and publish from 2.0 to 3.0
  update_frequency: 4.0
  publish_frequency: 2.0
  rolling_window: false
  always_send_full_costmap: false

  resolution: 0.05
  width: 60.0
  height: 60.0
  origin_x: 0.0
  origin_y: 0.0

  plugins:
    - {name: static_layer,      type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,    type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,   type: "costmap_2d::InflationLayer"}
