# http://wiki.ros.org/costmap_2d#costmap_2d.2BAC8-layered.Parameters
local_costmap:
#CHANGED FROM map to odom
  global_frame: odom
  robot_base_frame: fake
  transform_tolerance: 0.5
  # update from 2.0 to 4.0 and publish from 2.0 to 3.0
  update_frequency: 4.0
  publish_frequency: 3.0
  rolling_window: true
  always_send_full_costmap: false

  resolution: 0.05
  width: 4.0
  height: 4.0

  plugins: 
    - {name: obstacle_layer,    type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,   type: "costmap_2d::InflationLayer"}


#observation_sources: point_cloud_sensor

  # assuming receiving a cloud from rtabmap_ros/obstacles_detection node
  # topic was zed2/point_cloud/cloud_registered , /camera/depth/points_downsampled
  # expected update rate was 0.5
  # marking was true
  # LAST EDIT was testing the pc filter with slope detection and changed the topic to /points_filtered
  #   min_obstacle_height: 1.2,
  #max_obstacle_height: 2.0
#point_cloud_sensor: {
#  sensor_frame: fake/sensor_fake,
#  data_type: PointCloud2, 
#  topic: /points_filtered, 
#  expected_update_rate: 10.0, 
#  marking: true, 
#  clearing: true}
